apiVersion: external-secrets.io/v1alpha1
kind: ExternalSecret
metadata:
  name: social-information
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: awssm
  refreshInterval: 5m
  dataFrom:
    - key: dev/social-information/qadev/secrets
  target: {}